# Generated by Django 4.1.3 on 2022-11-19 16:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Educations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование образовательного учреждения')),
                ('start_date', models.TextField(verbose_name='Дата начала обучения')),
                ('end_date', models.TextField(verbose_name='Дата окончания обучения')),
                ('speciality', models.CharField(max_length=100, verbose_name='Специальность')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образование',
                'db_table': 'education',
            },
        ),
        migrations.CreateModel(
            name='Experiences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name_of_company', models.CharField(max_length=100, verbose_name='Компания')),
                ('experience', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Стаж')),
                ('start_date', models.TextField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.TextField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('position', models.CharField(max_length=100, verbose_name='Позиция')),
                ('responsibilities', models.TextField(verbose_name='Обязанности')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыт работы',
                'db_table': 'experience',
            },
        ),
        migrations.CreateModel(
            name='Resumes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('position', models.CharField(max_length=100, verbose_name='Позиция')),
                ('category', models.CharField(choices=[('other', 'Другое'), ('medicine', 'Медицина'), ('it', 'Информационные технологии'), ('marketing', 'Маркетинг'), ('science', 'Наука')], default='other', max_length=100, verbose_name='Сфера деятельности')),
                ('salary', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000000)], verbose_name='Уровень дохода')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telegram', models.URLField(verbose_name='Telegram')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Linkedin')),
                ('about_worker', models.TextField(blank=True, null=True, verbose_name='Обо мне')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Активность резюме')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('education', models.ManyToManyField(blank=True, related_name='worker_education', to='webapp.educations', verbose_name='Образование')),
                ('experience', models.ManyToManyField(blank=True, related_name='worker_experience', to='webapp.experiences', verbose_name='Опыт работы')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
                'db_table': 'resume',
            },
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('position', models.CharField(max_length=100, verbose_name='Позиция')),
                ('category', models.CharField(choices=[('other', 'Другое'), ('medicine', 'Медицина'), ('it', 'Информационные технологии'), ('marketing', 'Маркетинг'), ('science', 'Наука')], default='other', max_length=100, verbose_name='Категория')),
                ('salary', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000000)], verbose_name='Уровень дохода')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('min_experience', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Минимальный опыт')),
                ('max_experience', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Максимальный опыт')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Активность вакансии')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('resumes', models.ManyToManyField(blank=True, related_name='worker_resume', to='webapp.resumes', verbose_name='Резюме')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'db_table': 'vacancy',
            },
        ),
    ]
