# Generated by Django 4.1.3 on 2022-11-20 20:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0003_vacancies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL, verbose_name='Автор *'),
        ),
        migrations.AlterField(
            model_name='resumes',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email *'),
        ),
        migrations.AlterField(
            model_name='resumes',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия *'),
        ),
        migrations.AlterField(
            model_name='resumes',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя *'),
        ),
        migrations.AlterField(
            model_name='resumes',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Телефон *'),
        ),
        migrations.AlterField(
            model_name='resumes',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Позиция *'),
        ),
        migrations.AlterField(
            model_name='resumes',
            name='salary',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000000)], verbose_name='Уровень дохода *'),
        ),
        migrations.AlterField(
            model_name='resumes',
            name='telegram',
            field=models.URLField(verbose_name='Telegram *'),
        ),
    ]
