# Generated by Django 4.1.3 on 2022-11-23 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_message_respond_respondmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancies',
            name='resumes',
        ),
    ]
