# Generated by Django 4.1.3 on 2022-11-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_vacancies_resumes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumes',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='resumes',
            name='title',
            field=models.CharField(default=1, max_length=100, verbose_name='Наименование резюме *'),
            preserve_default=False,
        ),
    ]
