# Generated by Django 4.1.3 on 2022-11-24 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_rename_name_resumes_first_name_resumes_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respondmessage',
            name='message',
        ),
        migrations.AddField(
            model_name='respondmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Запись создана'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='respondmessage',
            name='text',
            field=models.CharField(blank=True, max_length=3000, null=True, verbose_name='Текст сообщения'),
        ),
        migrations.AddField(
            model_name='respondmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Запись изменена'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
