# Generated by Django 4.1.3 on 2022-11-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_account_phone_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта *'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Телефон *'),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Логин *'),
        ),
        migrations.AlterField(
            model_name='account',
            name='usertype',
            field=models.CharField(choices=[('company', 'Компания'), ('candidate', 'Кандидат')], max_length=250, verbose_name='Пользователь *'),
        ),
    ]
